version: "3.9"

services:
  mcp-github:
    image: ghcr.io/github/github-mcp-server
    container_name: mcp-github
    stdin_open: true
    tty: true
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_TOKEN}

  mcp-openai:
    build: ./openai
    container_name: mcp-openai
    stdin_open: true
    tty: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}

  mcp-filesystem:
    image: mcp/filesystem
    container_name: mcp-filesystem
    stdin_open: true
    tty: true
    volumes:
      - ./workspace:/projects/workspace
    command: ["mcp-server-filesystem", "/projects"]
